use_frameworks!
platform :ios, '9.0'

target 'AlamoRecord_Example' do
  pod 'AlamoRecord', :path => '../'
  pod 'SnapKit'
  pod 'NotificationBannerSwift', :git => 'https://github.com/Daltron/NotificationBanner', :branch => 'master'
  pod 'KeyboardSpy'
end

target 'Tests' do
    pod 'AlamoRecord', :path => '../'
end
