use_frameworks!
platform :ios, '9.0'

target 'AlamoRecord_Example' do
  pod 'AlamoRecord', :path => '../'
  pod 'SnapKit'
  pod 'NotificationBannerSwift'
  pod 'KeyboardSpy'
end

target 'Tests' do
    pod 'AlamoRecord', :path => '../'
end
